### ISSUE TITLE
Cannot import NotMasterError from pymongo.errors

### ISSUE THREAD

**Issue by Alge** [arngarden/MongoDBProxy#31]
Doens't seem to be compatible with Pymongo 4.3.3

```
Traceback (most recent call last):
  File "/home/...", line 34, in <module>
    import db
  File "/../db.py", line 2, in <module>
    import mongo_proxy
  File "/home/../env/lib/python3.11/site-packages/mongo_proxy/__init__.py", line 3, in <module>
    from .pymongo3_durable_cursor import PyMongo3DurableCursor
  File "/home/.../env/lib/python3.11/site-packages/mongo_proxy/pymongo3_durable_cursor.py", line 31, in <module>
    from pymongo.errors import NotMasterError
ImportError: cannot import name 'NotMasterError' from 'pymongo.errors' (/home/../env/lib/python3.11/site-packages/pymongo/errors.py)
(env) m
```

**Comment by Alge** [comment]
See PR  #32
